begin;

create table if not exists public.app_admins (
  email text primary key,
  role text not null default 'voditelj',
  active boolean not null default true,
  created_at timestamptz not null default now()
);

insert into public.app_admins (email)
select lower(email)
from auth.users
where email is not null
on conflict (email) do update set active = true;

alter table public.app_admins enable row level security;

create or replace function public.is_dashboard_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.app_admins
    where email = lower(coalesce(auth.jwt() ->> 'email', ''))
      and active = true
  );
$$;

revoke all on function public.is_dashboard_admin() from public;
grant execute on function public.is_dashboard_admin() to authenticated;

create table if not exists public.public_form_rate_limits (
  id bigint generated by default as identity primary key,
  fingerprint text not null,
  request_kind text not null,
  payload_hash text not null,
  created_at timestamptz not null default now()
);

create index if not exists public_form_rate_limits_lookup_idx
  on public.public_form_rate_limits (fingerprint, request_kind, created_at desc);

alter table public.public_form_rate_limits enable row level security;

revoke all on table public.app_admins from anon, authenticated;
grant select on table public.app_admins to authenticated;
drop policy if exists balent_admins_read_self on public.app_admins;
create policy balent_admins_read_self
  on public.app_admins
  for select
  to authenticated
  using (email = lower(coalesce(auth.jwt() ->> 'email', '')));

revoke all on table public.public_form_rate_limits from anon, authenticated;
revoke all on sequence public.public_form_rate_limits_id_seq from anon, authenticated;

commit;
